### ISSUE TITLE
wsjcpp prepare travis

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp#29]
Add a basic .travis.yml if not exists:

```
language: cpp

branches:
  only:
    - master

dist: bionic

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - pkg-config

# Build steps
script:
  - ./build_simple.sh
  - cd unit-tests.wsjcpp
  - ./build_simple.sh
  - ./unit-tests
```

Append to README.md
```
[![Build Status](https://api.travis-ci.com/wsjcpp/fast-fourier-transform.svg?branch=master)](https://travis-ci.com/wsjcpp/fast-fourier-transform) 
```
