### ISSUE TITLE
experemental feature: Minifier for c++ code

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp#59]
will be commands:

* `wsjcpp minifier do`

1. Analize the code
2. Read configuration from wsjcpp.yml
3. Remove all unused classes / functions / methods of classes (use also excludes)
4. Put all sources to the folder "wsjcpp.minifier" + CMakeList.txt
5. Build in wsjcpp.minifier

folder `wsjcpp.minifier` - add to `.gitignore`

* `wsjcpp minifier info` - print configurations

segment in wsjcpp.yml like a:

```
minifier:
  exclude:
    classes:
      - Some
    methods:
      - Some0::test
    functions:
      - ssss
    files:
      - ./src/some.cpp
      - ./src/some.h
```
* `wsjcpp minifier analize` - print result of analize (Classes / methods / functions) and statistics how much was called
* `wsjcpp minifier exclude add class Class` - add class to exclude
* `wsjcpp minifier exclude remove class Class` - remove class from exclude
* `wsjcpp minifier exclude add func FuncName` - add func to exclude
* `wsjcpp minifier exclude remove function FuncName` - remove func from exclude
* `wsjcpp minifier exclude add file FileName` - add file to exclude
* `wsjcpp minifier exclude remove file FileName` - remove file from exclude
