### ISSUE TITLE
Feature: exclude files from build for some package

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp#67]
Feature: exclude files from build for some package

Files which must be excluded from builds.

like this:
```
dependencies:
  - name: "wsjcpp-core"
    version: "v0.1.7"
    url: "https://github.com/wsjcpp/wsjcpp-core:master"
    origin: "https://github.com/"
    installation-dir: "./src.wsjcpp/wsjcpp_core"
    exlude-files:
       - 'wsjcpp_unit_tests.h'
       - 'wsjcpp_unit_tests.cpp'
```
