### ISSUE TITLE
improve: add new field 'installation-datetime' to dependence information

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp#75]
```
dependencies:
  - name: "wsjcpp-core"
    version: "v0.2.1"
    url: "https://github.com/wsjcpp/wsjcpp-core:master"
    origin: "https://github.com/"
    installation-dir: "./src.wsjcpp/wsjcpp_core"
    installation-datetime: "Wed, 30 Sep 2020 20:32:36 GMT"
```

Maybe helpful for detect correctly version when installed from master
