### ISSUE TITLE
feature: write file VERSION if enabled

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp#76]
On `wsjcpp update` must be created and updated file VERSION

Command for enable / disable
```
$ wsjcpp change version-file on
$ wsjcpp change version-file off
```
Support short commands:
```
$ wsjcpp ch ver-file on
$ wsjcpp ch ver-file off
```

Must be added new section to wsjcpp.yml:

```
auto-generated-files:
  version-file:
    path: "./"
    filename: "VERSION"
    printed-format: "v{MAJOR}.{MINOR}.{BUILD}"
```
