### ISSUE TITLE
improve add configurable "auto-generated-files"."src-wsjcpp" to wsjcpp.yml

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp#80]
Like this:
```
auto-generated-files:
  src-wsjcpp:
    path: "./src.wsjcpp/"
    include-cmakelists: true
    include-qmake-pri: false
```
