### ISSUE TITLE
improve add configurable "auto-generated-files"."unit-tests-wsjcpp" to wsjcpp.yml 

### ISSUE THREAD

**Issue by sea-kg** [wsjcpp/wsjcpp#81]
Like this:
```
auto-generated-files:
  unit-tests-wsjcpp:
    path: "./unit-tests.wsjcpp/"
    include-cmakelists: true
    include-qmake-pri: false
```
